### ISSUE TITLE
sqlite3: lld unknown argument --no-undefined

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#10]
This one does not seem to be a shortened flag.

**Comment by jeremyd2019** [comment]
This comes from https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-sqlite3/Makefile.ext.in#L30

**Comment by mati865** [comment]
`--no-undefined` is legit flag not supported by LLD's MinGW backend but we should be able to live without it (let's keep it for BFD).

**Comment by jeremyd2019** [comment]
> `--no-undefined` is legit flag not supported by LLD's MinGW backend but we should be able to live without it (let's keep it for BFD).

Please clarify.  Does that mean that there needs to be a conditional added to the PKGBUILD to take the flag out for clang/lld-based builds?  Or would it make more sense to add the flag as an ignored option like https://github.com/msys2/CLANG-packages/blob/83693f5e06de2d0566292a9037c8bdcc9a12ed78/mingw-w64-clang/0304-ignore-new-bfd-options.patch#L6-L12

**Comment by mati865** [comment]
`--no-undefined` is supported by BFD/GOLD/LLD when targeting ELF and at least accepted by BFD when targeting MinGW (I have no idea if it does anything).
I have no clue whether this flag is important or not for Windows but adding it as an ignored option could confuse build systems since it would appear as supported.
